package com.woniu.pojo;
// Generated 2019-12-17 16:37:33 by Hibernate Tools 3.5.0.Final

/**
 * Userssh generated by hbm2java
 */
@SuppressWarnings("serial")
public class Userssh implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private String upass;

	public Userssh() {
	}

	public Userssh(String uname, String upass) {
		this.uname = uname;
		this.upass = upass;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpass() {
		return this.upass;
	}

	public void setUpass(String upass) {
		this.upass = upass;
	}

}
